---
- hosts: rtr1
  gather_facts: no
  tasks:
    - name: Display File Contents (No output - Ephemeral containers are a problem)
      ansible.builtin.command: "cat /tmp/backup.cfg"
      ignore_errors: True
      register: result
    
    - debug:
        msg: "{{ result.stdout_lines }}"

    - name: Take running-config backup (with backup_option)
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: backup.cfg
          dir_path: /tmp
      register: backup

    - name: Display File Contents
      ansible.builtin.command: "cat /tmp/backup.cfg"
      ignore_errors: True
      register: result
    
    - debug:
        msg: "{{ result.stdout_lines }}"
    
    - name: remove non config lines - regexp - Part 1
      lineinfile:
        path: "/tmp/backup.cfg"
        line: "Building configuration..."
        state: absent

    - name: remove non config lines - regexp - Part 2
      lineinfile:
        path: "{{ backup.backup_path }}"
        line: "version 16.9"
        state: absent